"""Generate outputs/audit/dataset_report.html from the measured M1 artifacts only.

Every number is computed from manifests/*.parquet, outputs/audit/dataset_*.csv and
m1_inventory_facts.json. No face images are embedded (SiW-Mv2 DRA forbids public display).
No timestamps are embedded so the report is byte-deterministic for identical inputs.
"""
from __future__ import annotations

import collections
import csv
import html
import json
from pathlib import Path

import pyarrow.parquet as pq

E = html.escape


def _csv(path: Path) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _table(rows: list[dict], cols: list[str] | None = None) -> str:
    if not rows:
        return "<p class='muted'>(none)</p>"
    cols = cols or list(rows[0])
    head = "".join(f"<th>{E(c)}</th>" for c in cols)
    body = "".join("<tr>" + "".join(f"<td>{E(str(r.get(c, '')))}</td>" for c in cols) + "</tr>" for r in rows)
    return f"<div class='tw'><table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>"


CSS = """
:root{--bg:#fbfaf7;--fg:#1d1d1b;--muted:#6b6a65;--line:#dedbd2;--accent:#2f5d8a;--warn:#9a5b00;--bad:#a3261b;--ok:#2d6a3e}
@media (prefers-color-scheme:dark){:root{--bg:#161614;--fg:#ecebe6;--muted:#a3a19a;--line:#3a3934;--accent:#8fb6dd;--warn:#e0a651;--bad:#ef7d72;--ok:#7cc48f}}
body{background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,sans-serif;margin:0;padding:24px 16px;max-width:1100px;margin-inline:auto}
h1{font-size:1.6em;margin:0 0 4px}h2{font-size:1.2em;margin-top:2em;border-bottom:1px solid var(--line);padding-bottom:4px}
h3{font-size:1.02em;margin-top:1.4em}.muted{color:var(--muted)}.tw{overflow-x:auto}
table{border-collapse:collapse;font-size:13px;margin:8px 0}th,td{border:1px solid var(--line);padding:4px 8px;text-align:left;vertical-align:top}
th{background:color-mix(in srgb,var(--line) 40%,transparent)}code{font-size:12.5px}
.badge{display:inline-block;padding:1px 8px;border-radius:9px;font-size:12px;font-weight:600;border:1px solid}
.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}
"""


def write_report(cfg: dict, project_root: Path) -> Path:
    out = {k: project_root / v for k, v in cfg["outputs"].items()}
    videos = pq.read_table(out["inventory_videos"]).to_pylist()
    samples = pq.read_table(out["inventory"]).to_pylist()
    files = pq.read_table(out["raw_file_index"]).to_pylist()
    summary = _csv(out["summary_csv"])
    coverage = _csv(out["attack_coverage_csv"])
    unmapped = _csv(out["unmapped_csv"])
    issues = _csv(out["issues_csv"])
    archives = _csv(out["archive_csv"])
    dups = _csv(out["duplicates_csv"])
    facts = json.loads(out["facts_json"].read_text(encoding="utf-8"))
    by_ds = collections.defaultdict(list)
    for v in videos:
        by_ds[v["dataset"]].append(v)
    S = {r["dataset"]: r for r in summary}
    sid = [s["sample_id"] for s in samples]
    parts = [f"<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
             f"<title>M1 Dataset Inventory</title><style>{CSS}</style></head><body>",
             "<h1>GPAT-TransferBench — M1 dataset inventory report</h1>",
             "<p class='muted'>Generated by <code>gpatbench.data.report</code> from the measured inventory artifacts. "
             "Local inventory is the source of truth (spec §3.1). No benchmark TRAIN/VAL/TEST split exists at M1.</p>"]

    # A. Summary
    parts.append("<h2>A. Summary</h2>")
    parts.append(_table([{k: r[k] for k in ("dataset", "selected_root", "indexed_files", "canonical_videos", "unique_subjects",
                                              "live_videos", "spoof_videos", "attack_raw_types", "attack_macro_types_spoof",
                                              "sampled_frame_rows")} for r in summary]))
    parts.append(f"<p>Totals: {len(files)} indexed files, {len(videos)} canonical videos/sequences, {len(samples)} sampled-frame rows; "
                 f"duplicate sample_id: <b>{len(sid) - len(set(sid))}</b>.</p>")
    parts.append("<h3>Indexed files by category</h3>")
    parts.append(_table([{k: r[k] for k in r if k == "dataset" or k.startswith("files_") or k in ("unreadable_files", "total_bytes")}
                         for r in summary]))

    # B. Subject coverage
    parts.append("<h2>B. Subject coverage</h2>")
    parts.append(_table([{k: r[k] for k in ("dataset", "videos_with_subject_id", "videos_missing_subject_id", "unique_subjects",
                                              "unique_subjects_live", "unique_subjects_spoof")} for r in summary]))
    srcs = sorted({(v["dataset"], v["subject_id_status"], v["subject_id_source"]) for v in videos})
    parts.append(_table([{"dataset": a, "subject_id_status": b, "subject_id_source (rule)": c} for a, b, c in srcs]))

    # C. Attack coverage
    parts.append("<h2>C. Attack coverage</h2>")
    parts.append(_table(coverage))
    parts.append("<h3>Unmapped attack tokens (assigned other_spoof for the binary inventory only)</h3>")
    parts.append(_table(unmapped))

    # D. Dataset-specific findings
    parts.append("<h2>D. Dataset-specific findings</h2>")
    c = by_ds["casia_fasd"]
    cfile = [f for f in files if f["dataset"] == "casia_fasd"]
    codes = collections.Counter((json.loads(v["native_meta_json"])["class_dir"], json.loads(v["native_meta_json"])["video_code"]) for v in c)
    parts_ = collections.Counter(v["native_protocol_split"] for v in c)
    subj_nums = collections.defaultdict(set)
    for v in c:
        m = json.loads(v["native_meta_json"])
        subj_nums[m["partition"]].add(m["subject_number"])
    overlap = sorted(subj_nums["train"] & subj_nums["test"])
    sizes = collections.Counter(v["frame_sizes"] for v in c)
    dstats = facts.get("derived_copy_checks", {}).get("casia_fasd", {})
    parts.append("<h3>CASIA-FASD</h3><ul>"
                 f"<li>Local copy is a repackaged image-sequence version: {S['casia_fasd']['files_canonical_frame_image']} canonical frame PNGs; frame sizes {E(dict(sizes).__repr__())}. "
                 "No documentation file ships with this copy (all files are PNG).</li>"
                 f"<li>Folder layout <code>{{train|test}}/{{live|spoof}}/</code>; canonical sequences per native partition: {dict(parts_)}. "
                 f"Codes by class directory: {E(str(sorted(codes.items())))}.</li>"
                 f"<li>Subject numbers per partition: train {len(subj_nums['train'])}, test {len(subj_nums['test'])}; numbers present in both partitions: {len(overlap)}. "
                 "Rule: <code>subject_id_raw = {partition}_s{N}</code> (numbers restart per partition; see M1_DATASET_EVIDENCE.md).</li>"
                 f"<li>Derived copies (<code>bs*</code>/<code>fs*</code>, train/live only): {S['casia_fasd']['files_derived_augmentation_copy']} files, indexed but excluded from samples. "
                 f"Measured: {E(json.dumps(dstats, sort_keys=True))}.</li>"
                 f"<li>Attack parse rule: <code>attack_raw</code> = native video code; no local documentation maps codes to attack concepts, so all CASIA spoof codes are UNMAPPED (see C).</li>"
                 f"<li>Label conflicts: {S['casia_fasd']['label_conflict_videos']} videos (code HR_1 stored under <code>spoof/</code>).</li></ul>")
    m = by_ds["msu_mfsd"]
    splits = collections.Counter(v["native_protocol_split"] for v in m)
    cams = collections.Counter(json.loads(v["native_meta_json"])["camera"] for v in m)
    parts.append("<h3>MSU-MFSD</h3><ul>"
                 f"<li>Selected root is a <b>directory</b> named <code>MSU-MFSD-Publish.zip</code> (extracted copy); the multi-part archive pieces beside it are not used.</li>"
                 f"<li>{len(m)} videos; README naming protocol parsed for every video (unrecognised names fail the run).</li>"
                 f"<li>Native protocol lists (provenance only, not the benchmark split): videos per list {dict(splits)}.</li>"
                 f"<li>Cameras (audit only, never fed to generators): {dict(cams)}.</li>"
                 f"<li>.face annotation files: {sum(json.loads(v['native_meta_json'])['face_annotation_present'] for v in m)}/{len(m)} videos.</li></ul>")
    s = by_ds["siwmv2"]
    folders = collections.Counter(v["attack_raw"] for v in s if v["label_binary"] == 1)
    listing = facts.get("root_listings", {}).get("siwmv2", [])
    case_issues = [i for i in issues if i["dataset"] == "siwmv2" and i["code"] == "CASE_INSENSITIVE_PATH_COLLISION"]
    parts.append("<h3>SiW-Mv2</h3><ul>"
                 f"<li>Root listing: {E(str(listing))}. Case-insensitive path collisions under the root: {len(case_issues)}. "
                 "The M0 note about lowercase <code>live/</code>/<code>spoof/</code> was a misread of concatenated command output (those entries belong to CASIA <code>train/</code>).</li>"
                 f"<li>{sum(v['label_binary'] == 0 for v in s)} live and {sum(v['label_binary'] == 1 for v in s)} spoof videos across {len(folders)} attack folders: {E(str(sorted(folders.items())))}.</li>"
                 "<li>Subject identity is <b>not recoverable</b> from local files (filenames carry only per-class sequence numbers; README.pdf defers naming to an external link).</li></ul>")

    # E. Integrity
    parts.append("<h2>E. Integrity</h2>")
    sev = collections.Counter((i["dataset"], i["severity"], i["code"]) for i in issues)
    parts.append(_table([{"dataset": a, "severity": b, "code": cc, "count": n} for (a, b, cc), n in sorted(sev.items())]))
    parts.append("<h3>Archive cross-check (central directory size + CRC32 vs extracted files)</h3>")
    parts.append(_table(archives))
    within = sum(1 for d in dups if ";" not in d["datasets"])
    cross = sum(1 for d in dups if ";" in d["datasets"])
    parts.append(f"<h3>Exact-byte duplicates among canonical files</h3><p>{len(dups)} hash groups "
                 f"({within} within one dataset, {cross} across datasets); full list in <code>dataset_duplicate_hashes.csv</code>. "
                 "Groups spanning different canonical videos:</p>")
    parts.append(_table([d for d in dups if int(d["n_distinct_videos"]) > 1]))
    dec = collections.Counter((v["dataset"], v["decode_status"]) for v in videos)
    parts.append(_table([{"dataset": a, "decode_status": b, "videos": n} for (a, b), n in sorted(dec.items())]))
    parts.append(f"<p>Decoder: <code>{E(json.dumps(facts.get('decoder', {}), sort_keys=True))}</code></p>")

    # F. Preconditions
    parts.append("<h2>F. Preconditions for later milestones</h2>")
    pre = []
    for ds in ("casia_fasd", "msu_mfsd", "siwmv2"):
        r = S[ds]
        m3 = "BLOCKED_BY_MISSING_SUBJECT_ID" if int(r["videos_missing_subject_id"]) else (
            "BLOCKED_BY_LABEL_CONFLICT (owner decision)" if int(r["label_conflict_videos"]) else "READY (subject IDs recovered)")
        nat = "BLOCKED (unmapped tokens)" if int(r["unmapped_attack_tokens"]) else "READY"
        hard = sum(1 for v in by_ds[ds] if v["decode_status"] in ("OPEN_FAILED", "NO_DECODABLE_FRAMES"))
        m2 = ("READY (frame indices fixed for every video)" if hard == 0
              else f"CHECK ({hard} videos with no decodable frames)")
        if ds == "casia_fasd":
            m2 += "; inputs are 112x112 face crops (owner question for §4 SCRFD/crop)"
        pre.append({"dataset": ds, "M2 frame sampling": m2, "M3 subject-disjoint split": m3, "Native/Full attack labels": nat})
    parts.append(_table(pre))

    # G. Limitations
    parts.append("<h2>G. Limitations / blockers</h2><ul>"
                 "<li>Sampled-frame <code>sha256</code> is the original frame file hash for CASIA (image sequence); for video datasets it is null "
                 "(<code>PENDING_M2_CANONICAL_PNG</code>) until M2 extracts canonical PNGs.</li>"
                 "<li>Valid-frame definition (Q-04) is operational (see data_v1.yaml); frame indices depend on the pinned decoder.</li>"
                 "<li>CASIA local frames are 112×112 face crops, not the original videos; M2 detection/cropping on such inputs is an open question for the owner.</li>"
                 "</ul></body></html>\n")
    path = out["report_html"]
    path.write_text("".join(parts), encoding="utf-8")
    return path
